SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS EXCLASS;
CREATE TABLE EXCLASS (
	cno bigint(19) AUTO_INCREMENT NOT NULL PRIMARY KEY,
	cname varchar(20) NULL
 ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='班级';

DROP TABLE IF EXISTS EXAMINATION;
CREATE TABLE EXAMINATION (
	EXAMID bigint(19) AUTO_INCREMENT NOT NULL PRIMARY KEY,
	EXAMNAME varchar(128) NOT NULL,
	isOpen tinyint(2) NULL default 1
 ) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8 COMMENT='实验';

DROP TABLE IF EXISTS SCHOOLYEAR;
CREATE TABLE SCHOOLYEAR (
	SCHOOLYEARID bigint(19) AUTO_INCREMENT NOT NULL PRIMARY KEY,
	NAME varchar(50) NULL
 ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='学年';

DROP TABLE IF EXISTS QUESTION;
CREATE TABLE QUESTION (
	QUESID bigint(19) AUTO_INCREMENT NOT NULL PRIMARY KEY,
	QUESNAME varchar(128) NOT NULL,
	QUESCONTENT text NOT NULL,
	QUESEVAL text NULL,
	QUESANSWER text NULL,
	EXAMID bigint(19) NULL ,
	quesrequired text NULL,
	quespreq text NULL,
	resultcheck text NULL,
	resultquery text NULL,
	ifpostext bit NULL,
	postexttype int NULL
 ) ENGINE=InnoDB AUTO_INCREMENT=212 DEFAULT CHARSET=utf8 COMMENT='问题';

DROP TABLE IF EXISTS TERM;
CREATE TABLE TERM (
	TERMID bigint(19) AUTO_INCREMENT NOT NULL PRIMARY KEY,
	NAME varchar(50) NULL,
	SCHOOLYEARID bigint(19) NULL ,
	STARTDATE datetime NULL,
	WEEKS int NULL
 ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='学期';

DROP TABLE IF EXISTS CURRICULA;
CREATE TABLE CURRICULA (
	classno bigint(19) NULL,
	teacherid bigint(19) NULL,
	TERMID bigint(19) NULL ,
	SCHOOLYEARID bigint(19) NULL ,
	STARTWEEK int NULL,
	ENDWEEK int NULL,
	SECTION int NULL,
	WEEKDAY int NULL,
	CURRICULAID bigint(19) AUTO_INCREMENT NOT NULL  PRIMARY KEY
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='实验课表';

DROP TABLE IF EXISTS EXERCISEBOOK;
CREATE TABLE EXERCISEBOOK (
	EXERBOOKID bigint(19) AUTO_INCREMENT NOT NULL PRIMARY KEY,
	QUESID bigint(19) NOT NULL ,
	USERID bigint(19) NOT NULL ,
	ANSWER text NULL,
	POSTTIME datetime NULL,
	STARTTIME datetime NULL,
	EVAL varchar(10) NULL,
	postext text NULL,
	CURRICULAID bigint(19) NULL ,
	resultset text NULL
 ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='作业本';

DROP TABLE IF EXISTS EXAM_CURR;
CREATE TABLE EXAM_CURR (
	EXAM_CURR_ID bigint(19) AUTO_INCREMENT NOT NULL  PRIMARY KEY,
	EXAMID bigint(19) NULL ,
	WEEK int NULL,
	CURRICULAID bigint(19) NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='实验与课表联系';


